act-framework.bs
A couple comments:
- I added a definition of a _selector_, adapted from the definition in [CSS Selectors Level 4](https://drafts.csswg.org/selectors-4/#context).
- I kept the concept of _element or component_ from the placeholder description, but we might want to just say _element_?
- For HTML input data, I suggest we **must** use CSS selectors. Using XPath on DOM is not properly specified and would be limited to XPath 1.0. XPath 2.0 or 3.0 could be used on static XML serialization of HTML, but I don't think it is practically very relevant. (disclaimer: I actually _love_ XPath).
- I find this section depends a lot on what we'll describe in the "ACT Input Data" section, which is not yet specified. For now, I assumed we can speak of "HTML input data" for any kind of HTML, document or …
=> Content for the Selectors section

act-framework.bs
The consensus from the 12/14/16 meeting was to simplify this definition
to use plainer text. As well, Alistair asks to be careful about the use
of element vs. node.
Some simplified text suggestions:
"selectors are patterns used to select the element(s) you want to work
with." - Alistair
From CSS 3 Selectors, Selectors are patterns that match against elements
in a tree, and as such form one of several technologies that can be used
to select nodes in an XML document. Selectors have been optimized for
use with HTML and XML, and are designed to be usable in
performance-critical code.
From w3 Schools: In CSS, selectors are patterns used to select the
element(s) you want to style.
=> Update Selector definition

act-framework.bs
This update provides a proposal for the Rule outline. 
Trying not to be too prescriptive here but are we inherently being prescriptive by generating a rule outline? 
Moe
=> Rule outline

act-framework.bs
updates to the rule description to include scope and expand on the bullets are ready for review.
=> Update rule description

act-framework.bs
Ready for review and possibly merger.
=> Accessibility support data description

act-framework.bs
Propose to resolve:
https://github.com/w3c/wcag-act/issues/70
=> Propose update to Selector section

act-rules-format.bs
=> Expand accessibility requirements section

act-rules-format.bs
Bikeshed error revealed a mismatch in href and heading id. Updated to match #acc-support
=> Update Accessibility Support href to match heading id

act-rules-format.bs
Fix issue [#119](https://github.com/w3c/wcag-act/issues/119).
=> Closes #119 | Fix typo in act-rules-format.bs

act-rules-format.bs
Updated #output-selected-item to #output-test-target to allow Bikeshed to compile without errors.
=> Fixing anchor tag to allow latest draft to compile

act-rules-format.bs
The proposed changes are not critical, but I think they slightly clarify the "format vs. rule" difference.
=> Reword informative prose in the Introduction and Scope sections

act-rules-format.bs
=> Replace selector/steps with applicability/expecations

act-rules-format.bs
- simplify the prose about "technology agnostic" in the Scope section
- replace "could" by "can" in the scope section
- lower case "Accessibility Requirements" for consistency
=> Minor editorial simplifications + fixes

act-rules-format.bs
- remove the use of "requirements" (requirements for whom?)
- replace "organizations" by "any party involved in accessibilty testing"
(since this format may not only be used by organizations, but also
by individuals)
- replace "better" by "in a robust and undertandable manner" to be more
explicit
=> Reword the abstract

act-rules-format.bs
- remove "good and bad", which is mostly subjective
- reword "This is known" ("this" referred to what?)
- remove use of "may" and "should" in explanatory prose
- normalize the normative statements on ACT Rules
Also, I’m wondering if "significant accessibility support concerns" can be made more explicit?
=> Reword the Accessibility Support section

act-rules-format.bs
Change the example of the "Limitations" section to make it more explicit.
Fixes #136.
=> Improve the example of 'Limitations, Assumptions, or Exceptions'

.pr-preview.json
This PR "fixes" the PR Preview config by adding the `force` param to generate the spec even when Bikeshed raises errors.
***
<a href="https://pr-preview.s3.amazonaws.com/rdeltour/wcag-act/pull/254.html" title="Last updated on Sep 6, 2018, 7:08 AM GMT (3379077)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/254/1f76e23...rdeltour:3379077.html" title="Last updated on Sep 6, 2018, 7:08 AM GMT (3379077)">Diff</a>
=> Fix the PR Preview config

act-rules-format.bs
Remove "8.1 Common Aspects" to move it to a working group note. Insert link and examples in "8. Aspects under Test" instead.
In answer to https://github.com/w3c/wcag-act/issues/233.
***
<a href="https://pr-preview.s3.amazonaws.com/annethyme/wcag-act/pull/242.html" title="Last updated on Sep 13, 2018, 1:39 PM GMT (566ab45)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/242/54fc1ba...annethyme:566ab45.html" title="Last updated on Sep 13, 2018, 1:39 PM GMT (566ab45)">Diff</a>
=> Update "8. Aspects under Test"

act-rules-format.bs
Suggesting a different split of Applicability/Expectations sections for Atomic/Composed rules to get rid of headings "Test Defintion" and "Aggregation Definition"
Closes #237
***
<a href="https://pr-preview.s3.amazonaws.com/annethyme/wcag-act/pull/247.html" title="Last updated on Sep 17, 2018, 1:35 PM GMT (1f7d74b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/247/18630c3...annethyme:1f7d74b.html" title="Last updated on Sep 17, 2018, 1:35 PM GMT (1f7d74b)">Diff</a>
=> Get rid of "Test/Aggregation Definition"

act-rules-format.bs
Consistently use upper case for ACT Rules. This closes Issue #278
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/303.html" title="Last updated on Nov 15, 2018, 2:43 PM GMT (40bb9f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/303/af9a86b...40bb9f5.html" title="Last updated on Nov 15, 2018, 2:43 PM GMT (40bb9f5)">Diff</a>
=> Consistent use of ACT Rules

act-rules-format.bs
Addressing Issue 294 from TPAC discussion to remove formal syntax in 10.1, "When a formal syntax, such as a CSS selector [css3-selectors] or XML Path Language [XPATH], can be used, that (part of the) applicability MAY use that syntax in addition to the plain language description."
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/304.html" title="Last updated on Nov 15, 2018, 3:08 PM GMT (2a21fc5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/304/809e9f5...2a21fc5.html" title="Last updated on Nov 15, 2018, 3:08 PM GMT (2a21fc5)">Diff</a>
=> Remove formal syntax

act-rules-format.bs
Based on discussion of https://github.com/w3c/wcag-act/issues/293
***
<a href="https://pr-preview.s3.amazonaws.com/annethyme/wcag-act/pull/305.html" title="Last updated on Nov 29, 2018, 11:03 PM GMT (4bf90aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/305/809e9f5...annethyme:4bf90aa.html" title="Last updated on Nov 29, 2018, 11:03 PM GMT (4bf90aa)">Diff</a>
=> "Optional items" section + renaming "Assumptions"

act-rules-format.bs
Biblio tag CSS breaks Bikeshed. CSS2 works but is old. Using css-2018 for now until generic tag is supported.
=> Updating CSS Biblio Tag

act-rules-format.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/313.html" title="Last updated on Jan 13, 2019, 1:17 PM UTC (ede6f60)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/313/6ea8ddc...ede6f60.html" title="Last updated on Jan 13, 2019, 1:17 PM UTC (ede6f60)">Diff</a>
=> Accessibility requirements mapping rewrite

act-rules-format.bs
Fix  broken anchor, #rule-accuracy
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/337.html" title="Last updated on Feb 22, 2019, 4:02 AM UTC (152eed0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/337/18814ba...152eed0.html" title="Last updated on Feb 22, 2019, 4:02 AM UTC (152eed0)">Diff</a>
=> Fix  broken anchor, #rule-accuracy

act-rules-format.bs
Made all lowercase and enclosed in ` ` characters everywhere they appear.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/351.html" title="Last updated on Mar 28, 2019, 2:35 PM UTC (30ad42a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/351/6d77e5e...30ad42a.html" title="Last updated on Mar 28, 2019, 2:35 PM UTC (30ad42a)">Diff</a>
=> Fix styling, capitalization of outcomes

act-rules-format.bs
Update example to test for accessible names of HTML Input Elements.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/349.html" title="Last updated on Mar 21, 2019, 3:14 PM UTC (6f1ac95)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/349/6d77e5e...6f1ac95.html" title="Last updated on Mar 21, 2019, 3:14 PM UTC (6f1ac95)">Diff</a>
=> Issue 342 Example of HTML Input Element Accessible Name

act-rules-format.bs
Suggested edits to take care of Issue #323
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/350.html" title="Last updated on Mar 28, 2019, 2:33 PM UTC (6cdb437)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/350/6d77e5e...6cdb437.html" title="Last updated on Mar 28, 2019, 2:33 PM UTC (6cdb437)">Diff</a>
=> Made WCAG references consistent

act-rules-format.bs
Moved [Exit Criteria from wiki](https://www.w3.org/WAI/GL/task-forces/conformance-testing/wiki/Exit_Criteria_for_Rules_Format_Spec), which have been approved by the TF/WG, to this appendix so that it is within the same document for publication.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/352.html" title="Last updated on Mar 29, 2019, 5:09 PM UTC (0e19f39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/352/1de230e...0e19f39.html" title="Last updated on Mar 29, 2019, 5:09 PM UTC (0e19f39)">Diff</a>
=> added Exit Criteria

act-rules-format.bs
Changed example to better reflect the intention (aggregation by Success Criterion). Should address issue #362
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/377.html" title="Last updated on Jun 6, 2019, 12:43 PM UTC (de4f3bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/377/4bb10f3...de4f3bf.html" title="Last updated on Jun 6, 2019, 12:43 PM UTC (de4f3bf)">Diff</a>
=> updated Example 3 in Annex 1

act-rules-format.bs
Have "rule type" from section 4 link to section 4.3, rather than link back up to section 3.
Issue #375
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/387.html" title="Last updated on Jun 27, 2019, 2:53 PM UTC (ce394cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/387/4678ff3...ce394cb.html" title="Last updated on Jun 27, 2019, 2:53 PM UTC (ce394cb)">Diff</a>
=> Fix "rule type" link in section 4

act-rules-format.bs
Fixed two spots where "W" should be used and one spot where "w" should be used.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/379.html" title="Last updated on Jun 14, 2019, 10:10 PM UTC (d385d01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/379/4678ff3...d385d01.html" title="Last updated on Jun 14, 2019, 10:10 PM UTC (d385d01)">Diff</a>
=> Fixed capitalization in 3 places

act-rules-format.bs
Clarified that only if background info is added, it SHOULD contain the relationship info.  See Issue #355.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/380.html" title="Last updated on Jun 14, 2019, 10:37 PM UTC (f0080c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/380/4678ff3...f0080c4.html" title="Last updated on Jun 14, 2019, 10:37 PM UTC (f0080c4)">Diff</a>
=> Should explainer

act-rules-format.bs
Added in "An ACT Rule can also contain" before the optional parts.  Used "can" because I wasn't sure if I was allowed to add in normative language like "MAY" when we're in CR status. See Issue #357.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/382.html" title="Last updated on Jun 17, 2019, 2:34 PM UTC (3e09740)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/382/4678ff3...3e09740.html" title="Last updated on Jun 17, 2019, 2:34 PM UTC (3e09740)">Diff</a>
=> Optional items under must

act-rules-format.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/395.html" title="Last updated on Jul 8, 2019, 2:14 PM UTC (1336871)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/395/839e440...1336871.html" title="Last updated on Jul 8, 2019, 2:14 PM UTC (1336871)">Diff</a>
=> Put RFC2119 key words in styles

act-rules-format.bs
Closes #348 
- Consistent use of <blockquote>
- Added <header> for captions
- Aligned caption formulations
- Changed <div> to <aside>
- Misc typographical fixes
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/392.html" title="Last updated on Jul 8, 2019, 2:19 PM UTC (cd72f44)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/392/8a57d3d...cd72f44.html" title="Last updated on Jul 8, 2019, 2:19 PM UTC (cd72f44)">Diff</a>
=> align all examples

act-rules-format.bs
Editorial [comments from David McDonald](https://lists.w3.org/Archives/Public/w3c-wai-gl/2019JulSep/0048.html):
> MUST NOST
> should be "MUST NOT"
> 
> 4.8
> Example of a  rule that checks if aria-errormessage is used <add>to</add> satisfy WCAG 2.1 success criterion 4.1.3 Status messages :
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/404.html" title="Last updated on Jul 18, 2019, 9:32 AM UTC (8973bf8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/404/e5e24e1...8973bf8.html" title="Last updated on Jul 18, 2019, 9:32 AM UTC (8973bf8)">Diff</a>
=> fix typos identified by David McDonald

act-rules-format.bs
Assumptions: fixed link to QuickRef "WCAG 2.1 success criterion 1.4.3 Contrast" (anchor name changed from WCAG 2.0 to 2.1)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/403.html" title="Last updated on Jul 17, 2019, 4:18 PM UTC (e705195)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/403/e5e24e1...e705195.html" title="Last updated on Jul 17, 2019, 4:18 PM UTC (e705195)">Diff</a>
=> fixed broken link

act-rules-format.bs
Accessibility Support: fixed link to definition of "Accessibility Supported" in WCAG (anchor name changed from 2.0 to 2.1)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/401.html" title="Last updated on Jul 17, 2019, 4:14 PM UTC (a885893)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/401/e5e24e1...a885893.html" title="Last updated on Jul 17, 2019, 4:14 PM UTC (a885893)">Diff</a>
=> fixed link

act-rules-format.bs, act-rules-format.html
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jul 22, 2019, 2:36 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fwcag-act%2Fpull%2F408%2Fca174d2.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fwcag-act%2Fpull%2F408.html)
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html …
```
=> Clarify Appendix 3 is non-normative

act-rules-format.bs
changed wrong <header> to </header> in the example in "Accessibility Support"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/409.html" title="Last updated on Jul 22, 2019, 3:21 PM UTC (ce5f168)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/409/eb7eae8...ce5f168.html" title="Last updated on Jul 22, 2019, 3:21 PM UTC (ce5f168)">Diff</a>
=> fixing validation error

act-rules-format.bs
Closes #413 
Changed the link for Common Input Aspects WG Note in section 4.5.1 from Editor's Draft to Latest Published version.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/415.html" title="Last updated on Aug 18, 2019, 11:31 AM UTC (30f013d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/415/a756dfc...30f013d.html" title="Last updated on Aug 18, 2019, 11:31 AM UTC (30f013d)">Diff</a>
=> fixed link to Common Input Aspects WG Note

wcag-ruleset-review-process.md
As discussed during the TF call last week, the ACT Task Force is looking to distribute rule communication work between its members, instead of having most of the work done by one of the TF facilitators. This PR adds such a role to the review process.
=> Add the "liaison" role to review process

act-rules-format.bs
Using US Spelling
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/443.html" title="Last updated on Mar 26, 2020, 2:55 PM UTC (025924a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/443/44250c7...025924a.html" title="Last updated on Mar 26, 2020, 2:55 PM UTC (025924a)">Diff</a>
=> Acknowledgements -> Acknowledgments

act-rules-format.bs
The current definition is inconsistent in how it is used. While the intent was to include best practices as accessibility requirements, the current reading does not allow for this. The ACT rules format mentions explicitly that these can be best practices, so the definition is incorrect. This should resolve the issue.
Closes #424
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/450.html" title="Last updated on May 14, 2020, 1:29 PM UTC (d74f86a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/450/627e269...d74f86a.html" title="Last updated on May 14, 2020, 1:29 PM UTC (d74f86a)">Diff</a>
=> editorial: fix inconsistency in accessibility requirement

w3c.json
w3c.json expects a top-level group, not a task force identifier
=> Fix w3c.json group

act-rules-format/act-rules-format.bs
Update secondary requirements explanation to [Move secondary requirement texts out of the background #2060](https://github.com/act-rules/act-rules.github.io/pull/2060)
=> Update act-rules-format.bs for secondary requirements explanation

act-rules-format/act-rules-format.bs
Follow-up of #522 (which was out of date and had merge issues)
=> Add optional Implementations section

act-rules-format/act-rules-format.bs
Add Secondary requirements and accessibility support conclusion from https://github.com/act-rules/act-rules.github.io/discussions/2095
=> Update act-rules-format.bs for secondary req and acc support

act-rules-format/act-rules-format.bs
Based on feedback @dbjorge: from https://github.com/w3c/wcag/issues/3616#issuecomment-1896487077
I agree that `cantTell` was too low down the list. If a check reports `pass` and `cantTell`, it's incorrect to conclude that's a pass. It wouldn't work for satisfying rules. I think it does not go above `untested` though. Any `untested` outcome should prevent a check from getting mapped as `consistent`, and if we put `cantTell` before `untested` that wouldn't happen; Checks can be consistent when they report `cantTell` as long as that isn't the only thing they report.
=> Consistency: Prioritize cantTell over pass

act-rules-format/act-rules-format.bs, common-input-aspects/NOTE-act-rules-common-aspects.bs
=> Fixes #565 -- Refers to WCAG 2.2 consistently throughout

act-rules-format/act-rules-format.bs
This PR:
- fixes some classes that missed quotes around them
- removes manual numbering of examples that clashed with Bikeshed automatic processing
- Removes the word "Example" from each of the headers, as it is automatically provided by Bikeshed
- added markup for examples in appendix 1: Expressing ACT Rule results with JSON-LD and EARL {#appendix-data-example}
-
=> Example numbering is confusing Fixes #563
