w3c/wcag-act

act-framework.bs
Feedback from ACT meeting. Rule description should read:
Each ACT Rule MUST have a description that:
- Is in plain language;
- Explains the accessibility requirement being tested;
- Lists any limitations and assumptions for the test;
- Explains the failure conditions and their reasons.
=> Update to Rule Description

README.md
In order to gain contributor access, i made the minor change to the readme to add a link to the latest draft.
=> Added link to the latest draft

act-framework.bs
- Remove white/blackbox testing references
- Renamed a few of the input types for clearity
=> Update input type

act-framework.bs
Pull updates from master to build latest working draft 2-20-2017.
=> Latest working draft 2-20-2017

act-framework.bs
Add separate for accessibility requirements and limitations / assumptions / exceptions for the test under rule description.
=> Mangaging exceptions

act-framework.bs
Original draft of Test cases section per issue #29.
=> Test cases - Issue #29

act-framework.bs
Updates to Abstract, Intro and Scope to include editorial and grammatical updates. In attendance, Kathy W., Wilco, Mary Jo, Charu and Moe.
=> CSUN 2017 Working meeting - 02-28-2017

act-framework.bs
Updates to Intro based upon feedback from AGWG Survey and proposed text at 3/15/17 meeting. See Issue #71 for full details.
=> Update to intro issue71

act-rules-format.bs
Changed second false positives to false negatives. Also, believe we want percentage (singular) vs. percentages (plural).
=> Fix double false positive statements

act-rules-format.bs
Updated outcome of "cannot tell" to "undetermined"
=> Outcomes undetermined

act-rules-format.bs
Generating latest editor's draft
=> Generating latest editor's draft

act-rules-format.bs
=> Accessibility support

act-rules-format.bs
Need to generate latest draft for review before sending out next public working draft.
=> Generating latest draft for review 8-14-17

act-rules-format.bs
Including Editor's note and Generating Second Public Work Draft for AWAG review.
=> Generating Public Working Draft

act-rules-format.bs
This pull request addresses issue #103 opened 7/31/17 to re-word test cases to test execution steps.
=> Re-word Test cases to Test execution steps

act-rules-format.bs
Move Accessibility Support section to align with Rule Outline per Issue #137
=> Move Accessibility Support

act-rules-format.bs
This pull request addresses Issue #129 Typo if Benchmarking Section and Issue #135 Updates to statements in Section 3.3. Accessibility Requirements as proposed at TPAC.
=> Editorial updates Typo in 9.2 and Updates to Accessibility Requirements 3.3

act-rules-format.bs
=> Replace "selected item" with "test target"

act-rules-format.bs
=> Replace Undetermined with CannotTell

act-rules-format.bs
Generating latest working draft
=> Generate lastest working draft - 11/28/17

act-rules-format.bs
=> Add note on unique identifiers

act-rules-format.bs
Updated the language as suggested in Issue #132.
=> Update Rule outline text per issue 132

act-rules-format.bs
=> Ensure EARL examples are valid

act-rules-format.bs
=> Aspects under test

act-rules-format.bs
- replace occurences of "Each ACT Rule" by "An ACT Rule"
- add a normative statement to section 3.4 "Limitations"
Fixes #134.
=> Normalize the statements on ACT Rules

act-rules-format.bs
I did a fair amount of editorial updates to simplify, add punctuation, fix spelling errors. I also reordered the data output sections to match the bulleted list in the output section.
=> Editorial updates, fix spelling errors.

act-rules-format.bs
=> Test definitions

act-rules-format.bs
=> change: expectation is an assertion

act-rules-format.bs
1. We need to be consistent with either with the word "products"  or "tools" used in this section.
2. Removed additional words that add cognitive load the sentence.
3. Usually, in QA terms we say "Testing Tools" instead of "Test Tools".
=> Update Introduction Section

act-rules-format.bs
Applies the change proposed in #167.
Fixes #167.
=> Editorial simplification in 'Common Aspects'

act-rules-format.html
@nitedog I modified your edits to the last sentence a little bit, as it doesn't promote harmonized standards but a harmonized understanding of what is required.  See if you like it.
=> Shadi's updates to the Abstract section

act-rules-format.bs
***
<a href="https://pr-preview.s3.amazonaws.com/rdeltour/wcag-act/pull/287.html" title="Last updated on Nov 15, 2018, 2:13 PM GMT (e747908)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/287/758bbcb...rdeltour:e747908.html" title="Last updated on Nov 15, 2018, 2:13 PM GMT (e747908)">Diff</a>
=> Typos and minor editorial tweaks

act-rules-format.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/308.html" title="Last updated on Nov 29, 2018, 2:35 PM GMT (8242cad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/308/809e9f5...8242cad.html" title="Last updated on Nov 29, 2018, 2:35 PM GMT (8242cad)">Diff</a>
=> Added Acknowledgments section

NOTE-act-rules-common-aspects.bs
- Changed heading levels to make document more flat
- Changed from "Working Group Note" to "Editor Draft"
=> revising document structure

NOTE-act-rules-common-aspects.bs
fleshed out the Abstract and Introduction for first publication.
=> updated Abstract and Introduction

act-rules-format.bs
@WilcoFiers Rolled back composite-composite rules and the findings vs. outcomes.  I finished up the changes we discussed and left off at the new Note I wrote on line 318.  Please check what I wrote for the note to make sure I accurately captured it from today's meeting.  Let me know if we need to meet again and I can pick up some more changes to do from you.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/328.html" title="Last updated on Feb 21, 2019, 6:01 PM UTC (8b6c1a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/328/79a05b3...8b6c1a7.html" title="Last updated on Feb 21, 2019, 6:01 PM UTC (8b6c1a7)">Diff</a>
=> Candidate recommendation proposal

act-rules-format.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/332.html" title="Last updated on Feb 21, 2019, 3:35 PM UTC (2efdbd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/332/53fc457...2efdbd3.html" title="Last updated on Feb 21, 2019, 3:35 PM UTC (2efdbd3)">Diff</a>
=> Created a change history for the document.

act-rules-format.bs
Closes #341
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/343.html" title="Last updated on Mar 20, 2019, 8:11 PM UTC (24fb968)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/343/152eed0...24fb968.html" title="Last updated on Mar 20, 2019, 8:11 PM UTC (24fb968)">Diff</a>
=> edit: Change test aspect to input aspect

act-rules-format.bs
Closes #98
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/347.html" title="Last updated on Mar 21, 2019, 2:31 PM UTC (afbe97d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/347/152eed0...afbe97d.html" title="Last updated on Mar 21, 2019, 2:31 PM UTC (afbe97d)">Diff</a>
=> edit: Better changelog example

act-rules-format.bs
Closes #315
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/345.html" title="Last updated on Mar 20, 2019, 8:52 PM UTC (9ba6330)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/345/152eed0...9ba6330.html" title="Last updated on Mar 20, 2019, 8:52 PM UTC (9ba6330)">Diff</a>
=> edit: Update use of outcome definition

act-rules-format.bs
Closes #331
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/344.html" title="Last updated on Mar 20, 2019, 8:38 PM UTC (466eaef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/344/152eed0...466eaef.html" title="Last updated on Mar 20, 2019, 8:38 PM UTC (466eaef)">Diff</a>
=> edit: More examples for expectations

act-rules-format.bs
Issue #358
Issue #360
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/385.html" title="Last updated on Jun 27, 2019, 2:52 PM UTC (60f35ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/385/4678ff3...60f35ee.html" title="Last updated on Jun 27, 2019, 2:52 PM UTC (60f35ee)">Diff</a>
=> Add inline definition for unique identifier

act-rules-format.bs
Issue #372 
Issue #373
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/388.html" title="Last updated on Jun 26, 2019, 4:46 PM UTC (8606893)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/388/4678ff3...8606893.html" title="Last updated on Jun 26, 2019, 4:46 PM UTC (8606893)">Diff</a>
=> Remove unintended must & may

act-rules-format.bs
Closes #361
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/386.html" title="Last updated on Jun 26, 2019, 4:29 PM UTC (8ad1b10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/386/4678ff3...8ad1b10.html" title="Last updated on Jun 26, 2019, 4:29 PM UTC (8ad1b10)">Diff</a>
=> Change "vue" reference to "web component"

act-implementations.html
Changing from "Implementation Plan" to "Implementation Report" for further review and refinement.
=> Prepare Implementation Report

act-rules-format.bs
Tweaks to address the second bullet of issue #364 (removing "fully-automated, semi-automated, and manual testing" because they are not defined)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/376.html" title="Last updated on Jun 6, 2019, 12:31 PM UTC (4e45a78)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/376/4bb10f3...4e45a78.html" title="Last updated on Jun 6, 2019, 12:31 PM UTC (4e45a78)">Diff</a>
=> updated abstract

act-rules-format.bs
See issue #356.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/381.html" title="Last updated on Jun 14, 2019, 10:54 PM UTC (a07e890)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/381/4678ff3...a07e890.html" title="Last updated on Jun 14, 2019, 10:54 PM UTC (a07e890)">Diff</a>
=> Made various editorial changes

act-rules-format.bs
Closes #335 and addresses #364 
Some more elaboration on the example, and clarification of the use case and motivation for this.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/393.html" title="Last updated on Jul 2, 2019, 10:50 AM UTC (8b2dc56)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/393/246a6c7...8b2dc56.html" title="Last updated on Jul 2, 2019, 10:50 AM UTC (8b2dc56)">Diff</a>
=> clariying note on complex aggregation

act-rules-format.bs
Rearranged paragraphs and added a few minor grammar edits. See Issue #363 for the problem description.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/383.html" title="Last updated on Jul 8, 2019, 2:38 PM UTC (a404d5d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/383/e506b83...a404d5d.html" title="Last updated on Jul 8, 2019, 2:38 PM UTC (a404d5d)">Diff</a>
=> Edits to clarify Input Aspects

act-rules-format.bs
- Removed references to Auto-WCAG and added context, to address issue #378 
- Refined examples, descriptions, and link to further information on EARL/JSON, to address issue #366
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/389.html" title="Last updated on Jul 8, 2019, 4:24 PM UTC (8073320)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/389/aac0a4d...8073320.html" title="Last updated on Jul 8, 2019, 4:24 PM UTC (8073320)">Diff</a>
=> update Appendix 1

act-rules-format.bs
More details to "Change History" section
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/397.html" title="Last updated on Jul 12, 2019, 8:52 AM UTC (c399ed6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/397/5740677...c399ed6.html" title="Last updated on Jul 12, 2019, 8:52 AM UTC (c399ed6)">Diff</a>
=> Change History

act-rules-format.bs
Closes #384
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/406.html" title="Last updated on Jul 18, 2019, 1:31 PM UTC (026eb76)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/406/e5e24e1...026eb76.html" title="Last updated on Jul 18, 2019, 1:31 PM UTC (026eb76)">Diff</a>
=> Add "and higher" to required for conformance example

act-rules-format.html
=> fixed typo

README.md, act-rules-format.bs, act-rules-format.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/410.html" title="Last updated on Jul 22, 2019, 5:10 PM UTC (ea99bdf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/410/eb7eae8...ea99bdf.html" title="Last updated on Jul 22, 2019, 5:10 PM UTC (ea99bdf)">Diff</a>
=> Creating updated WG Note

NOTE-act-rules-common-aspects.bs
Update URLs to point to TR version.
=> Update Common Input Aspects URLs

NOTE-act-rules-common-aspects.bs, README.md, act-rules-format.bs
Generating updated draft with urls to TR definitions in Intro. Also, adding Mary Jo and Shadi as editors.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/pull/423.html" title="Last updated on Nov 18, 2019, 4:02 PM UTC (7a59a2d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag-act/423/ea99bdf...7a59a2d.html" title="Last updated on Nov 18, 2019, 4:02 PM UTC (7a59a2d)">Diff</a>
=> Generating updated draft with URLs to TR

wcag-ruleset-review-process.md
As discussed in https://github.com/w3c/wcag-act/issues/458
=> Add implementation requirements to process

.github/workflows/auto-publish.yml
Includes GitHub action that:
* Updates editor draft in PR and push to main branch
=> First attempt at auto-publish GitHub action

act-rules-format/act-rules-format.bs
=> Superceeds #533 Fix typo on the word "provided"

act-rules-format/act-rules-format.bs, common-input-aspects/NOTE-act-rules-common-aspects.bs
=> Fix markdown ids

act-rules-format/act-rules-format.bs
=> Add note to glossary

act-rules-format/act-rules-format.bs
@kengdoj @WilcoFiers  This superceeds #581
=> Update sec req placement and other definitions

act-rules-format/act-rules-format.bs
=> Qualify "writing direction" statement

act-rules-format/act-rules-format.bs
=> Qualify identifier uniqueness prose

act-rules-format/act-rules-format.bs
Replace test case with example
=> Update act-rules-format 1.1 to rename test cases to examples
